# Build intake catalog for ATLAS v2.5 datasets

In [1]:
import pandas as pd
import numpy as np

In [2]:
## load manifest

df = pd.read_csv("../atlas_v2.5/manifest-atlas-v25_20260520.txt", names=["url"])
df

                                                    url
0     https://data.mips.climate.copernicus.eu/thredd...
1     https://data.mips.climate.copernicus.eu/thredd...
2     https://data.mips.climate.copernicus.eu/thredd...
3     https://data.mips.climate.copernicus.eu/thredd...
4     https://data.mips.climate.copernicus.eu/thredd...
...                                                 ...
1026  https://data.mips.climate.copernicus.eu/thredd...
1027  https://data.mips.climate.copernicus.eu/thredd...
1028  https://data.mips.climate.copernicus.eu/thredd...
1029  https://data.mips.climate.copernicus.eu/thredd...
1030  https://data.mips.climate.copernicus.eu/thredd...

[1031 rows x 1 columns]

In [3]:
df.url[0]

'https://data.mips.climate.copernicus.eu/thredds/fileServer/esg_c3s-cica-atlas/v025/CMIP6/historical/evspsbl_CMIP6_historical_mon_185001-201412_v025.nc'

In [4]:
## build new dataframe

df_new = pd.DataFrame(columns = [
    'ds_id',
    'version',
    'path',
    'size',
    'project',
    'domain',
    'experiment',
    'time_frequency',
    'variable_id',
    'variable',
    'bias_adjustment',
    'start_time',
    'end_time',
    'bbox',
    'level',
    'url',
])
df_new

Empty DataFrame
Columns: [ds_id, version, path, size, project, domain, experiment, time_frequency, variable_id, variable, bias_adjustment, start_time, end_time, bbox, level, url]
Index: []

In [5]:
# df_new["url"] = df["url"].str.replace("/esg_c3s-cica-atlas/v02", "/esg_c3s-cica-atlas/v02", regex=False)
df_new["url"] = df["url"]
df_new.head()

,ds_id,version,path,size,project,domain,experiment,time_frequency,variable_id,variable,bias_adjustment,start_time,end_time,bbox,level,url
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...

In [6]:
df_new["path"] = df_new["url"].str.replace("https://data.mips.climate.copernicus.eu/thredds/fileServer/esg_c3s-cica-atlas/", "", regex=False)
df_new.head()

,ds_id,version,path,size,project,domain,experiment,time_frequency,variable_id,variable,bias_adjustment,start_time,end_time,bbox,level,url
0,NaN,NaN,v025/CMIP6/historical/evspsbl_CMIP6_historical...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
1,NaN,NaN,v025/CMIP6/historical/dtr_CMIP6_historical_mon...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
2,NaN,NaN,v025/CMIP6/historical/tx_CMIP6_historical_mon_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
3,NaN,NaN,v025/CMIP6/historical/sst_CMIP6_historical_mon...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
4,NaN,NaN,v025/CMIP6/historical/rx1day_CMIP6_historical_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...

In [7]:
version = "v25"

df_new["ds_id"] = df_new["path"].apply(lambda x: 'c3s-cica-atlas.' + '.'.join(x.split('/')[-1].split('_')[0:-2]) + '.' + version)
df_new.head()

,ds_id,version,path,size,project,domain,experiment,time_frequency,variable_id,variable,bias_adjustment,start_time,end_time,bbox,level,url
0,c3s-cica-atlas.evspsbl.CMIP6.historical.mon.v25,NaN,v025/CMIP6/historical/evspsbl_CMIP6_historical...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
1,c3s-cica-atlas.dtr.CMIP6.historical.mon.v25,NaN,v025/CMIP6/historical/dtr_CMIP6_historical_mon...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
2,c3s-cica-atlas.tx.CMIP6.historical.mon.v25,NaN,v025/CMIP6/historical/tx_CMIP6_historical_mon_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
3,c3s-cica-atlas.sst.CMIP6.historical.mon.v25,NaN,v025/CMIP6/historical/sst_CMIP6_historical_mon...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
4,c3s-cica-atlas.rx1day.CMIP6.historical.mon.v25,NaN,v025/CMIP6/historical/rx1day_CMIP6_historical_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...

In [8]:
df_new.ds_id[0]

'c3s-cica-atlas.evspsbl.CMIP6.historical.mon.v25'

In [9]:
# Let’s agree on “Europe” for E-OBS, “Europe (EURO-CORDEX)” for CORDEX-EUR-11 and “Global (mosaic)” for CODEX-CORE (the others are all “Global”).

def get_project(ds_id):
    project = ds_id.split(".")[2]
    # project = project.split("-")[0]
    return project

def get_domain(ds_id):
    project = ds_id.split(".")[2]
    if project == "E-OBS":
        domain = "Europe"
    elif project == "CORDEX-EUR-11":
        domain = "Europe (EURO-CORDEX)"
    elif project == "CORDEX-CORE":
        domain = "Global (mosaic)"
    else:
        domain = "Global"
    return domain

def get_experiment(ds_id):
    parts = ds_id.split('.')
    # print(parts, len(parts))
    if len(parts) == 6:
        exp = parts[3]
    else:
        exp = np.nan
    return exp
    

def get_start_time(path):
    parts = path.split("_")
    part = parts[-2]
    start = part.split("-")[0]
    if "mon" in parts:
        start_time = f"{start[0:4]}-{start[4:6]}-01T00:00:00"
    else:
        start_time = f"{start[0:4]}-01-01T00:00:00"
    return start_time


def get_end_time(path):
    # print(path)
    parts = path.split("_")
    # print(parts)
    part = parts[-2]
    # print(part)
    end = part.split("-")[1]
    if "mon" in parts:
        end_time = f"{end[0:4]}-{end[4:6]}-31T00:00:00"
    else:
        end_time = f"{end[0:4]}-12-31T00:00:00"
    return end_time

def get_version(ds_id):
    return "v25"

In [10]:
df_new['version'] = df_new['ds_id'].apply(get_version)
df_new['project'] = df_new["ds_id"].apply(get_project)
df_new['domain'] = df_new["ds_id"].apply(get_domain)
df_new['experiment'] = df_new["ds_id"].apply(get_experiment)
df_new['time_frequency'] = df_new["ds_id"].apply(lambda x: x.split('.')[-2])
df_new['variable_id'] = df_new["ds_id"].apply(lambda x: x.split('.')[1])
df_new['start_time'] = df_new["path"].apply(get_start_time)
df_new['end_time'] = df_new["path"].apply(get_end_time)
df_new

,ds_id,version,path,size,project,domain,experiment,time_frequency,variable_id,variable,bias_adjustment,start_time,end_time,bbox,level,url
0,c3s-cica-atlas.evspsbl.CMIP6.historical.mon.v25,v25,v025/CMIP6/historical/evspsbl_CMIP6_historical...,NaN,CMIP6,Global,historical,mon,evspsbl,NaN,NaN,1850-01-01T00:00:00,2014-12-31T00:00:00,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
1,c3s-cica-atlas.dtr.CMIP6.historical.mon.v25,v25,v025/CMIP6/historical/dtr_CMIP6_historical_mon...,NaN,CMIP6,Global,historical,mon,dtr,NaN,NaN,1850-01-01T00:00:00,2014-12-31T00:00:00,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
2,c3s-cica-atlas.tx.CMIP6.historical.mon.v25,v25,v025/CMIP6/historical/tx_CMIP6_historical_mon_...,NaN,CMIP6,Global,historical,mon,tx,NaN,NaN,1850-01-01T00:00:00,2014-12-31T00:00:00,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
3,c3s-cica-atlas.sst.CMIP6.historical.mon.v25,v25,v025/CMIP6/historical/sst_CMIP6_historical_mon...,NaN,CMIP6,Global,historical,mon,sst,NaN,NaN,1850-01-01T00:00:00,2014-12-31T00:00:00,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
4,c3s-cica-atlas.rx1day.CMIP6.historical.mon.v25,v25,v025/CMIP6/historical/rx1day_CMIP6_historical_...,NaN,CMIP6,Global,historical,mon,rx1day,NaN,NaN,1850-01-01T00:00:00,2014-12-31T00:00:00,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1026,c3s-cica-atlas.txx.BERKELEY.mon.v25,v25,v025/BERKELEY/txx_BERKELEY_mon_188101-201712_v...,NaN,BERKELEY,Global,NaN,mon,txx,NaN,NaN,1881-01-01T00:00:00,2017-12-31T00:00:00,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
1027,c3s-cica-atlas.tn.BERKELEY.mon.v25,v25,v025/BERKELEY/tn_BERKELEY_mon_188101-201712_v0...,NaN,BERKELEY,Global,NaN,mon,tn,NaN,NaN,1881-01-01T00:00:00,2017-12-31T00:00:00,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
1028,c3s-cica-atlas.hd.BERKELEY.yr.v25,v25,v025/BERKELEY/hd_BERKELEY_yr_1881-2017_v025.nc,NaN,BERKELEY,Global,NaN,yr,hd,NaN,NaN,1881-01-01T00:00:00,2017-12-31T00:00:00,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
1029,c3s-cica-atlas.tx40.BERKELEY.mon.v25,v25,v025/BERKELEY/tx40_BERKELEY_mon_188101-201712_...,NaN,BERKELEY,Global,NaN,mon,tx40,NaN,NaN,1881-01-01T00:00:00,2017-12-31T00:00:00,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
1030,c3s-cica-atlas.tnn.BERKELEY.mon.v25,v25,v025/BERKELEY/tnn_BERKELEY_mon_188101-201712_v...,NaN,BERKELEY,Global,NaN,mon,tnn,NaN,NaN,1881-01-01T00:00:00,2017-12-31T00:00:00,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...

In [11]:
# Function to split variable_id name into variable and bias_adjusment
def split_bias(variable_id):
    if 'bals' in variable_id:
        return variable_id.replace('bals', ''), 'bals'
    elif 'baisimip' in variable_id:
        return variable_id.replace('baisimip', ''), 'baisimip'
    else:
        return variable_id, None

df_new[['variable', 'bias_adjustment']] = df_new['variable_id'].apply(lambda x: pd.Series(split_bias(x)))

df_new

,ds_id,version,path,size,project,domain,experiment,time_frequency,variable_id,variable,bias_adjustment,start_time,end_time,bbox,level,url
0,c3s-cica-atlas.evspsbl.CMIP6.historical.mon.v25,v25,v025/CMIP6/historical/evspsbl_CMIP6_historical...,NaN,CMIP6,Global,historical,mon,evspsbl,evspsbl,None,1850-01-01T00:00:00,2014-12-31T00:00:00,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
1,c3s-cica-atlas.dtr.CMIP6.historical.mon.v25,v25,v025/CMIP6/historical/dtr_CMIP6_historical_mon...,NaN,CMIP6,Global,historical,mon,dtr,dtr,None,1850-01-01T00:00:00,2014-12-31T00:00:00,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
2,c3s-cica-atlas.tx.CMIP6.historical.mon.v25,v25,v025/CMIP6/historical/tx_CMIP6_historical_mon_...,NaN,CMIP6,Global,historical,mon,tx,tx,None,1850-01-01T00:00:00,2014-12-31T00:00:00,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
3,c3s-cica-atlas.sst.CMIP6.historical.mon.v25,v25,v025/CMIP6/historical/sst_CMIP6_historical_mon...,NaN,CMIP6,Global,historical,mon,sst,sst,None,1850-01-01T00:00:00,2014-12-31T00:00:00,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
4,c3s-cica-atlas.rx1day.CMIP6.historical.mon.v25,v25,v025/CMIP6/historical/rx1day_CMIP6_historical_...,NaN,CMIP6,Global,historical,mon,rx1day,rx1day,None,1850-01-01T00:00:00,2014-12-31T00:00:00,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1026,c3s-cica-atlas.txx.BERKELEY.mon.v25,v25,v025/BERKELEY/txx_BERKELEY_mon_188101-201712_v...,NaN,BERKELEY,Global,NaN,mon,txx,txx,None,1881-01-01T00:00:00,2017-12-31T00:00:00,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
1027,c3s-cica-atlas.tn.BERKELEY.mon.v25,v25,v025/BERKELEY/tn_BERKELEY_mon_188101-201712_v0...,NaN,BERKELEY,Global,NaN,mon,tn,tn,None,1881-01-01T00:00:00,2017-12-31T00:00:00,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
1028,c3s-cica-atlas.hd.BERKELEY.yr.v25,v25,v025/BERKELEY/hd_BERKELEY_yr_1881-2017_v025.nc,NaN,BERKELEY,Global,NaN,yr,hd,hd,None,1881-01-01T00:00:00,2017-12-31T00:00:00,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
1029,c3s-cica-atlas.tx40.BERKELEY.mon.v25,v25,v025/BERKELEY/tx40_BERKELEY_mon_188101-201712_...,NaN,BERKELEY,Global,NaN,mon,tx40,tx40,None,1881-01-01T00:00:00,2017-12-31T00:00:00,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
1030,c3s-cica-atlas.tnn.BERKELEY.mon.v25,v25,v025/BERKELEY/tnn_BERKELEY_mon_188101-201712_v...,NaN,BERKELEY,Global,NaN,mon,tnn,tnn,None,1881-01-01T00:00:00,2017-12-31T00:00:00,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...

## show values

In [12]:
df_new.nunique()

ds_id              1031
version               1
path               1031
size                  0
project              12
domain                4
experiment            9
time_frequency        2
variable_id          54
variable             35
bias_adjustment       2
start_time           11
end_time              9
bbox                  0
level                 0
url                1031
dtype: int64

In [13]:
list(df_new.version.unique())

['v25']

In [14]:
list(df_new.project.unique())

['CMIP6',
 'E-OBS',
 'CMIP5',
 'CERRA',
 'ERA5-Land',
 'SSTSAT',
 'ORAS5',
 'CORDEX-CORE',
 'CORDEX-EUR-11',
 'CPC',
 'ERA5',
 'BERKELEY']

In [15]:
list(df_new.domain.unique())

['Global', 'Europe', 'Global (mosaic)', 'Europe (EURO-CORDEX)']

In [16]:
list(df_new.experiment.unique())

['historical',
 'ssp126',
 'ssp119',
 'ssp245',
 'ssp585',
 'ssp370',
 nan,
 'rcp45',
 'rcp85',
 'rcp26']

In [17]:
list(df_new.time_frequency.unique())

['mon', 'yr']

In [18]:
list(df_new.variable_id.unique())

['evspsbl',
 'dtr',
 'tx',
 'sst',
 'rx1day',
 'r20baisimip',
 'tx40',
 'hdbaisimip',
 'siconc',
 'tr',
 'cdd',
 'tx40bals',
 'tx35bals',
 'dtrbals',
 'spi6',
 'sdiibaisimip',
 'cdbals',
 'rsds',
 'tx40baisimip',
 'trbaisimip',
 'fd',
 'r',
 'sfcwind',
 'cd',
 't',
 'mrro',
 'pet',
 'spei6',
 'r01baisimip',
 'tn',
 'psl',
 'r10baisimip',
 'cdbaisimip',
 'tx35',
 'rlds',
 'fdbaisimip',
 'hdbals',
 'clt',
 'dtrbaisimip',
 'r20',
 'fdbals',
 'mrsos',
 'rx5day',
 'txx',
 'prsn',
 'r10',
 'hd',
 'tx35baisimip',
 'r01',
 'tnn',
 'trbals',
 'cddbaisimip',
 'huss',
 'sdii']

In [19]:
list(df_new.variable.unique())

['evspsbl',
 'dtr',
 'tx',
 'sst',
 'rx1day',
 'r20',
 'tx40',
 'hd',
 'siconc',
 'tr',
 'cdd',
 'tx35',
 'spi6',
 'sdii',
 'cd',
 'rsds',
 'fd',
 'r',
 'sfcwind',
 't',
 'mrro',
 'pet',
 'spei6',
 'r01',
 'tn',
 'psl',
 'r10',
 'rlds',
 'clt',
 'mrsos',
 'rx5day',
 'txx',
 'prsn',
 'tnn',
 'huss']

In [20]:
list(df_new.bias_adjustment.unique())

[None, 'baisimip', 'bals']

In [21]:
list(df_new.start_time.unique())

['1850-01-01T00:00:00',
 '2015-01-01T00:00:00',
 '1950-01-01T00:00:00',
 '2006-01-01T00:00:00',
 '1985-01-01T00:00:00',
 '1982-01-01T00:00:00',
 '1958-01-01T00:00:00',
 '1970-01-01T00:00:00',
 '1979-01-01T00:00:00',
 '1940-01-01T00:00:00',
 '1881-01-01T00:00:00']

In [22]:
list(df_new.end_time.unique())

['2014-12-31T00:00:00',
 '2100-12-31T00:00:00',
 '2024-12-31T00:00:00',
 '2021-12-31T00:00:00',
 '2005-12-31T00:00:00',
 '2025-12-31T00:00:00',
 '2022-12-31T00:00:00',
 '2020-12-31T00:00:00',
 '2017-12-31T00:00:00']

## Write new catalog

In [23]:
from datetime import datetime

last_updated = datetime.now().utcnow()
version = last_updated.strftime('v%Y%m%d')
cat_name = f"c3s-cica-atlas-v025_{version}.csv.gz"
cat_path = f"../intake/catalogs/c3s-atlas/{cat_name}"

df_new.to_csv(cat_path, index=False, compression="gzip")

/var/folders/tp/zjk02gcn2qj09cn7kw8gqqh40000gn/T/ipykernel_92468/953499447.py:3: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  last_updated = datetime.now().utcnow()