# CMIP6 Catalog: fix cesm2 psl

Date: 2026.02.03

Fix issue with cesm2 psl:

https://github.com/roocs/rook/issues/289

It has a redundant file (psl_day_CESM2_historical_r1i1p1f1_gn_18500101-20150101.nc):

```
du -sh /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/*
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_18500101-18591231.nc
6.7G    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_18500101-20150101.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_18600101-18691231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_18700101-18791231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_18800101-18891231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_18900101-18991231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_19000101-19091231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_19100101-19191231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_19200101-19291231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_19300101-19391231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_19400101-19491231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_19500101-19591231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_19600101-19691231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_19700101-19791231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_19800101-19891231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_19900101-19991231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_20000101-20091231.nc
206M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_20100101-20150101.nc
```

In [10]:
import intake
import pandas as pd

In [11]:
cat_url = "https://raw.githubusercontent.com/cp4cds/c3s_34g_manifests/master/intake/catalogs/c3s.yaml"
#cat_url = "https://github.com/cp4cds/c3s_34g_manifests/raw/add-fixes-for-cmip6-cordex/intake/catalogs/c3s.yaml"

cat = intake.open_catalog(cat_url)
list(cat)

['c3s-cmip5',
 'c3s-cmip5-daily-pressure-level',
 'c3s-cmip5-daily-single-level',
 'c3s-cmip5-monthly-pressure-level',
 'c3s-cmip5-monthly-single-level',
 'c3s-cmip6',
 'c3s-cmip6-decadal',
 'c3s-cordex',
 'c3s-ipcc-atlas',
 'c3s-cica-atlas-v01',
 'c3s-cica-atlas']

## Load CMIP6 catalog

In [12]:
df_cmip6 = cat['c3s-cmip6'].read()
df_cmip6

,ds_id,path,size,mip_era,activity_id,institution_id,source_id,experiment_id,member_id,table_id,variable_id,grid_label,version,start_time,end_time,bbox,level
0,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431515502,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1860-01-01T00:00:00,1869-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
1,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431429952,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1870-01-01T00:00:00,1879-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
2,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431367520,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1880-01-01T00:00:00,1889-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
3,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431336563,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1890-01-01T00:00:00,1899-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
4,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431427018,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1900-01-01T00:00:00,1909-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
5,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431417362,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1910-01-01T00:00:00,1919-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
6,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431462467,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1920-01-01T00:00:00,1929-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
7,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431403078,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1930-01-01T00:00:00,1939-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
8,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431460703,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1940-01-01T00:00:00,1949-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
9,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431433326,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1950-01-01T00:00:00,1959-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
10,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431579697,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1960-01-01T00:00:00,1969-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
11,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431465920,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1970-01-01T00:00:00,1979-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
12,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431433219,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1980-01-01T00:00:00,1989-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
13,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431418070,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1990-01-01T00:00:00,1999-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
14,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431350958,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,2000-01-01T00:00:00,2009-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
15,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,215795656,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,2010-01-01T00:00:00,2015-01-01T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
16,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431386422,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1850-01-01T00:00:00,1859-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN

In [13]:
df_cmip6.nunique()

ds_id              1
path              17
size              17
mip_era            1
activity_id        1
institution_id     1
source_id          1
experiment_id      1
member_id          1
table_id           1
variable_id        1
grid_label         1
version            1
start_time        17
end_time          17
bbox               1
level              0
dtype: int64

In [5]:
group_cols = [
    "mip_era",
    "activity_id",
    "institution_id",
    "source_id",
    "experiment_id",
    "member_id",
    "table_id",
    "variable_id",
    "grid_label",
    "version",
]

In [6]:
def drop_full_range_files(df, group_cols):
    to_drop = []

    for _, g in df.groupby(group_cols):
        if len(g) <= 1:
            continue

        min_start = g.start_time.min()
        max_end   = g.end_time.max()

        mask = (g.start_time == min_start) & (g.end_time == max_end)

        # Drop only if exactly one file spans the full range
        if mask.sum() == 1:
            to_drop.extend(g.loc[mask].index)

    return df.drop(index=to_drop)

In [7]:
df_psl = df_cmip6.loc[
    (df_cmip6.source_id == "CESM2") &
    (df_cmip6.variable_id == "psl")
]

df_new = drop_full_range_files(df_psl, group_cols)
df_new

,ds_id,path,size,mip_era,activity_id,institution_id,source_id,experiment_id,member_id,table_id,variable_id,grid_label,version,start_time,end_time,bbox,level
0,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431515502,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1860-01-01T00:00:00,1869-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
1,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431429952,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1870-01-01T00:00:00,1879-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
2,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431367520,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1880-01-01T00:00:00,1889-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
3,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431336563,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1890-01-01T00:00:00,1899-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
4,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431427018,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1900-01-01T00:00:00,1909-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
5,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431417362,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1910-01-01T00:00:00,1919-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
6,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431462467,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1920-01-01T00:00:00,1929-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
7,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431403078,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1930-01-01T00:00:00,1939-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
8,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431460703,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1940-01-01T00:00:00,1949-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
9,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431433326,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1950-01-01T00:00:00,1959-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
10,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431579697,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1960-01-01T00:00:00,1969-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
11,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431465920,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1970-01-01T00:00:00,1979-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
12,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431433219,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1980-01-01T00:00:00,1989-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
13,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431418070,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1990-01-01T00:00:00,1999-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
14,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431350958,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,2000-01-01T00:00:00,2009-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
15,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,215795656,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,2010-01-01T00:00:00,2015-01-01T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
16,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431386422,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1850-01-01T00:00:00,1859-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN

In [8]:
df_new.nunique()

ds_id              1
path              17
size              17
mip_era            1
activity_id        1
institution_id     1
source_id          1
experiment_id      1
member_id          1
table_id           1
variable_id        1
grid_label         1
version            1
start_time        17
end_time          17
bbox               1
level              0
dtype: int64

## Write fixed catalog

In [9]:
from datetime import datetime, UTC

last_updated = datetime.now(UTC)
version = last_updated.strftime('v%Y%m%d')
cat_name = f"c3s-cmip6_{version}.csv.gz"
cat_path = f"../intake/catalogs/c3s-cmip6/{cat_name}"

df_new.to_csv(cat_path, index=False, compression="gzip")