# CMIP6 Catalog: fix cesm2 psl

Date: 2026.02.03

Fix issue with cesm2 psl:

https://github.com/roocs/rook/issues/289

It has a redundant file (psl_day_CESM2_historical_r1i1p1f1_gn_18500101-20150101.nc):

```
du -sh /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/*
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_18500101-18591231.nc
6.7G    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_18500101-20150101.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_18600101-18691231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_18700101-18791231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_18800101-18891231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_18900101-18991231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_19000101-19091231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_19100101-19191231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_19200101-19291231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_19300101-19391231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_19400101-19491231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_19500101-19591231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_19600101-19691231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_19700101-19791231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_19800101-19891231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_19900101-19991231.nc
412M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_20000101-20091231.nc
206M    /mnt/lustre/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn/v20190308/psl_day_CESM2_historical_r1i1p1f1_gn_20100101-20150101.nc
```

In [1]:
import intake
import pandas as pd

In [2]:
cat_url = "https://raw.githubusercontent.com/cp4cds/c3s_34g_manifests/master/intake/catalogs/c3s.yaml"
#cat_url = "https://github.com/cp4cds/c3s_34g_manifests/raw/add-fixes-for-cmip6-cordex/intake/catalogs/c3s.yaml"

cat = intake.open_catalog(cat_url)
list(cat)

['c3s-cmip5',
 'c3s-cmip5-daily-pressure-level',
 'c3s-cmip5-daily-single-level',
 'c3s-cmip5-monthly-pressure-level',
 'c3s-cmip5-monthly-single-level',
 'c3s-cmip6',
 'c3s-cmip6-decadal',
 'c3s-cordex',
 'c3s-ipcc-atlas',
 'c3s-cica-atlas-v01',
 'c3s-cica-atlas']

## Load CMIP6 catalog

In [3]:
df_cmip6 = cat['c3s-cmip6'].read()
df_cmip6

,ds_id,path,size,mip_era,activity_id,institution_id,source_id,experiment_id,member_id,table_id,variable_id,grid_label,version,start_time,end_time,bbox,level
0,c3s-cmip6.ScenarioMIP.MOHC.UKESM1-0-LL.ssp245....,ScenarioMIP/MOHC/UKESM1-0-LL/ssp245/r1i1p1f2/A...,28037112,c3s-cmip6,ScenarioMIP,MOHC,UKESM1-0-LL,ssp245,r1i1p1f2,Amon,ts,gn,v20190507,2015-01-16T00:00:00,2049-12-16T00:00:00,"0.94, -89.38, 359.06, 89.38",NaN
1,c3s-cmip6.ScenarioMIP.MOHC.UKESM1-0-LL.ssp245....,ScenarioMIP/MOHC/UKESM1-0-LL/ssp245/r1i1p1f2/A...,38838222,c3s-cmip6,ScenarioMIP,MOHC,UKESM1-0-LL,ssp245,r1i1p1f2,Amon,ts,gn,v20190507,2050-01-16T00:00:00,2100-12-16T00:00:00,"0.94, -89.38, 359.06, 89.38",NaN
2,c3s-cmip6.ScenarioMIP.NCAR.CESM2.ssp370.r4i1p1...,ScenarioMIP/NCAR/CESM2/ssp370/r4i1p1f1/Amon/pr...,104081588,c3s-cmip6,ScenarioMIP,NCAR,CESM2,ssp370,r4i1p1f1,Amon,pr,gn,v20200528,2015-01-15T12:00:00,2064-12-15T12:00:00,"0.00, -90.00, 358.75, 90.00",NaN
3,c3s-cmip6.ScenarioMIP.NCAR.CESM2.ssp370.r4i1p1...,ScenarioMIP/NCAR/CESM2/ssp370/r4i1p1f1/Amon/pr...,74977662,c3s-cmip6,ScenarioMIP,NCAR,CESM2,ssp370,r4i1p1f1,Amon,pr,gn,v20200528,2065-01-15T12:00:00,2100-12-15T12:00:00,"0.00, -90.00, 358.75, 90.00",NaN
4,c3s-cmip6.ScenarioMIP.AS-RCEC.TaiESM1.ssp370.r...,ScenarioMIP/AS-RCEC/TaiESM1/ssp370/r1i1p1f1/Am...,144277888,c3s-cmip6,ScenarioMIP,AS-RCEC,TaiESM1,ssp370,r1i1p1f1,Amon,rlut,gn,v20201014,2015-01-16T12:00:00,2100-12-16T12:00:00,"0.00, -90.00, 358.75, 90.00",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132993,c3s-cmip6.CMIP.MIROC.MIROC-ES2H.historical.r1i...,CMIP/MIROC/MIROC-ES2H/historical/r1i1p4f2/Amon...,204026121,c3s-cmip6,CMIP,MIROC,MIROC-ES2H,historical,r1i1p4f2,Amon,tauu,gn,v20220322,1850-01-16T12:00:00,2014-12-16T12:00:00,"0.00, -88.93, 358.59, 88.93",NaN
132994,c3s-cmip6.CMIP.MIROC.MIROC-ES2H.historical.r1i...,CMIP/MIROC/MIROC-ES2H/historical/r1i1p4f2/Amon...,164344947,c3s-cmip6,CMIP,MIROC,MIROC-ES2H,historical,r1i1p4f2,Amon,rlus,gn,v20220322,1850-01-16T12:00:00,2014-12-16T12:00:00,"0.00, -88.93, 358.59, 88.93",NaN
132995,c3s-cmip6.CMIP.MIROC.MIROC-ES2H.historical.r1i...,CMIP/MIROC/MIROC-ES2H/historical/r1i1p4f2/Amon...,3420481903,c3s-cmip6,CMIP,MIROC,MIROC-ES2H,historical,r1i1p4f2,Amon,ua,gn,v20220322,1850-01-16T12:00:00,2014-12-16T12:00:00,"0.00, -88.93, 358.59, 88.93",100.00 500.00 1000.00 2000.00 3000.00 5000.00 ...
132996,c3s-cmip6.CMIP.MIROC.MIROC-ES2H.historical.r1i...,CMIP/MIROC/MIROC-ES2H/historical/r1i1p4f2/Amon...,143468073,c3s-cmip6,CMIP,MIROC,MIROC-ES2H,historical,r1i1p4f2,Amon,tasmin,gn,v20220322,1850-01-16T12:00:00,2014-12-16T12:00:00,"0.00, -88.93, 358.59, 88.93",2.00
132997,c3s-cmip6.CMIP.MIROC.MIROC-ES2H.historical.r1i...,CMIP/MIROC/MIROC-ES2H/historical/r1i1p4f2/Amon...,86270014,c3s-cmip6,CMIP,MIROC,MIROC-ES2H,historical,r1i1p4f2,Amon,prsn,gn,v20220322,1850-01-16T12:00:00,2014-12-16T12:00:00,"0.00, -88.93, 358.59, 88.93",NaN

In [4]:
df_cmip6.nunique()

ds_id              10357
path              132998
size              122268
mip_era                1
activity_id            2
institution_id        31
source_id             58
experiment_id          9
member_id             15
table_id               8
variable_id           51
grid_label             3
version              237
start_time           624
end_time             665
bbox                  54
level                  6
dtype: int64

In [5]:
df = df_cmip6.loc[
    (df_cmip6.source_id=="CESM2" )
    & (df_cmip6.table_id=="day")
    & (df_cmip6.variable_id=="psl")
    & (df_cmip6.experiment_id=="historical")
]
df

,ds_id,path,size,mip_era,activity_id,institution_id,source_id,experiment_id,member_id,table_id,variable_id,grid_label,version,start_time,end_time,bbox,level
62617,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,7118009724,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1850-01-01T00:00:00,2015-01-01T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62625,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431515502,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1860-01-01T00:00:00,1869-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62633,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431429952,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1870-01-01T00:00:00,1879-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62641,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431367520,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1880-01-01T00:00:00,1889-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62649,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431336563,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1890-01-01T00:00:00,1899-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62657,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431427018,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1900-01-01T00:00:00,1909-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62665,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431417362,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1910-01-01T00:00:00,1919-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62673,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431462467,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1920-01-01T00:00:00,1929-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62681,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431403078,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1930-01-01T00:00:00,1939-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62689,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431460703,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1940-01-01T00:00:00,1949-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62697,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431433326,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1950-01-01T00:00:00,1959-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62705,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431579697,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1960-01-01T00:00:00,1969-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62713,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431465920,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1970-01-01T00:00:00,1979-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62721,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431433219,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1980-01-01T00:00:00,1989-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62729,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431418070,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1990-01-01T00:00:00,1999-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62737,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431350958,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,2000-01-01T00:00:00,2009-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62745,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,215795656,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,2010-01-01T00:00:00,2015-01-01T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62819,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431386422,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1850-01-01T00:00:00,1859-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN

In [6]:
df.nunique()

ds_id              1
path              18
size              18
mip_era            1
activity_id        1
institution_id     1
source_id          1
experiment_id      1
member_id          1
table_id           1
variable_id        1
grid_label         1
version            1
start_time        17
end_time          17
bbox               1
level              0
dtype: int64

In [7]:
df_new = df.query(
    "not (start_time == '1850-01-01T00:00:00' and end_time == '2015-01-01T00:00:00')"
)
df_new

,ds_id,path,size,mip_era,activity_id,institution_id,source_id,experiment_id,member_id,table_id,variable_id,grid_label,version,start_time,end_time,bbox,level
62625,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431515502,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1860-01-01T00:00:00,1869-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62633,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431429952,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1870-01-01T00:00:00,1879-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62641,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431367520,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1880-01-01T00:00:00,1889-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62649,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431336563,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1890-01-01T00:00:00,1899-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62657,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431427018,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1900-01-01T00:00:00,1909-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62665,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431417362,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1910-01-01T00:00:00,1919-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62673,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431462467,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1920-01-01T00:00:00,1929-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62681,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431403078,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1930-01-01T00:00:00,1939-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62689,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431460703,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1940-01-01T00:00:00,1949-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62697,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431433326,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1950-01-01T00:00:00,1959-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62705,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431579697,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1960-01-01T00:00:00,1969-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62713,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431465920,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1970-01-01T00:00:00,1979-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62721,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431433219,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1980-01-01T00:00:00,1989-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62729,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431418070,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1990-01-01T00:00:00,1999-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62737,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431350958,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,2000-01-01T00:00:00,2009-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62745,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,215795656,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,2010-01-01T00:00:00,2015-01-01T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN
62819,c3s-cmip6.CMIP.NCAR.CESM2.historical.r1i1p1f1....,CMIP/NCAR/CESM2/historical/r1i1p1f1/day/psl/gn...,431386422,c3s-cmip6,CMIP,NCAR,CESM2,historical,r1i1p1f1,day,psl,gn,v20190308,1850-01-01T00:00:00,1859-12-31T00:00:00,"0.00, -90.00, 358.75, 90.00",NaN

In [8]:
df_new.nunique()

ds_id              1
path              17
size              17
mip_era            1
activity_id        1
institution_id     1
source_id          1
experiment_id      1
member_id          1
table_id           1
variable_id        1
grid_label         1
version            1
start_time        17
end_time          17
bbox               1
level              0
dtype: int64

## Write fixed catalog

In [9]:
from datetime import datetime, UTC

last_updated = datetime.now(UTC)
version = last_updated.strftime('v%Y%m%d')
cat_name = f"c3s-cmip6_{version}.csv.gz"
cat_path = f"../intake/catalogs/c3s-cmip6/{cat_name}"

df_new.to_csv(cat_path, index=False, compression="gzip")