# CORDEX Catalog: add 2 columns

Adding two new columns in the CORDEX intake with a separate 'region' (ARC, EUR...) and 'horizontal_resolution' (44, 11...).

date: 2026-01-07

In [1]:
import intake
import pandas as pd
import re

In [2]:
cat_url = "https://raw.githubusercontent.com/cp4cds/c3s_34g_manifests/master/intake/catalogs/c3s.yaml"

cat = intake.open_catalog(cat_url)
list(cat)

['c3s-cmip5',
 'c3s-cmip5-daily-pressure-level',
 'c3s-cmip5-daily-single-level',
 'c3s-cmip5-monthly-pressure-level',
 'c3s-cmip5-monthly-single-level',
 'c3s-cmip6',
 'c3s-cmip6-decadal',
 'c3s-cordex',
 'c3s-ipcc-atlas',
 'c3s-cica-atlas-v01',
 'c3s-cica-atlas']

In [3]:
df_cordex = cat['c3s-cordex'].read()
df_cordex.head()

,ds_id,path,size,project,domain,institute,driving_model,experiment_id,ensemble,rcm_name,rcm_version,time_frequency,variable,version,start_time,end_time,bbox,level,url
0,c3s-cordex.output.ARC-44.UQAM.ECMWF-ERAINT.eva...,output/ARC-44/UQAM/ECMWF-ERAINT/evaluation/r1i...,NaN,c3s-cordex,ARC-44,UQAM,ECMWF-ERAINT,evaluation,r1i1p1,UQAM-CRCM5,v1,fx,sftlf,v20200915,NaN,NaN,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
1,c3s-cordex.output.ARC-44.UQAM.ECMWF-ERAINT.eva...,output/ARC-44/UQAM/ECMWF-ERAINT/evaluation/r1i...,NaN,c3s-cordex,ARC-44,UQAM,ECMWF-ERAINT,evaluation,r1i1p1,UQAM-CRCM5,v1,fx,orog,v20200915,NaN,NaN,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
2,c3s-cordex.output.ARC-44.UQAM.ECMWF-ERAINT.eva...,output/ARC-44/UQAM/ECMWF-ERAINT/evaluation/r1i...,NaN,c3s-cordex,ARC-44,UQAM,ECMWF-ERAINT,evaluation,r1i1p1,UQAM-CRCM5,v1,day,clt,v20200915,1981-01-01T00:00:00,1985-12-31T00:00:00,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
3,c3s-cordex.output.ARC-44.UQAM.ECMWF-ERAINT.eva...,output/ARC-44/UQAM/ECMWF-ERAINT/evaluation/r1i...,NaN,c3s-cordex,ARC-44,UQAM,ECMWF-ERAINT,evaluation,r1i1p1,UQAM-CRCM5,v1,day,clt,v20200915,1991-01-01T00:00:00,1995-12-31T00:00:00,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...
4,c3s-cordex.output.ARC-44.UQAM.ECMWF-ERAINT.eva...,output/ARC-44/UQAM/ECMWF-ERAINT/evaluation/r1i...,NaN,c3s-cordex,ARC-44,UQAM,ECMWF-ERAINT,evaluation,r1i1p1,UQAM-CRCM5,v1,day,clt,v20200915,2001-01-01T00:00:00,2005-12-31T00:00:00,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...

In [4]:
df_cordex.nunique()

ds_id              23488
path              568405
size                   0
project                1
domain                27
institute             39
driving_model         17
experiment_id          5
ensemble               6
rcm_name              56
rcm_version           11
time_frequency         6
variable              25
version              144
start_time          1149
end_time            2016
bbox                   0
level                  0
url               568405
dtype: int64

## Add two new columns derived from domain

domain = {region}-{horizontal_resolution}

In [5]:
df_cordex[["region", "horizontal_resolution"]] = (
    df_cordex["domain"]
    .astype("string")
    .str.split("-", n=1, expand=True)
)
df_cordex.head()

,ds_id,path,size,project,domain,institute,driving_model,experiment_id,ensemble,rcm_name,...,time_frequency,variable,version,start_time,end_time,bbox,level,url,region,horizontal_resolution
0,c3s-cordex.output.ARC-44.UQAM.ECMWF-ERAINT.eva...,output/ARC-44/UQAM/ECMWF-ERAINT/evaluation/r1i...,NaN,c3s-cordex,ARC-44,UQAM,ECMWF-ERAINT,evaluation,r1i1p1,UQAM-CRCM5,...,fx,sftlf,v20200915,NaN,NaN,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...,ARC,44
1,c3s-cordex.output.ARC-44.UQAM.ECMWF-ERAINT.eva...,output/ARC-44/UQAM/ECMWF-ERAINT/evaluation/r1i...,NaN,c3s-cordex,ARC-44,UQAM,ECMWF-ERAINT,evaluation,r1i1p1,UQAM-CRCM5,...,fx,orog,v20200915,NaN,NaN,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...,ARC,44
2,c3s-cordex.output.ARC-44.UQAM.ECMWF-ERAINT.eva...,output/ARC-44/UQAM/ECMWF-ERAINT/evaluation/r1i...,NaN,c3s-cordex,ARC-44,UQAM,ECMWF-ERAINT,evaluation,r1i1p1,UQAM-CRCM5,...,day,clt,v20200915,1981-01-01T00:00:00,1985-12-31T00:00:00,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...,ARC,44
3,c3s-cordex.output.ARC-44.UQAM.ECMWF-ERAINT.eva...,output/ARC-44/UQAM/ECMWF-ERAINT/evaluation/r1i...,NaN,c3s-cordex,ARC-44,UQAM,ECMWF-ERAINT,evaluation,r1i1p1,UQAM-CRCM5,...,day,clt,v20200915,1991-01-01T00:00:00,1995-12-31T00:00:00,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...,ARC,44
4,c3s-cordex.output.ARC-44.UQAM.ECMWF-ERAINT.eva...,output/ARC-44/UQAM/ECMWF-ERAINT/evaluation/r1i...,NaN,c3s-cordex,ARC-44,UQAM,ECMWF-ERAINT,evaluation,r1i1p1,UQAM-CRCM5,...,day,clt,v20200915,2001-01-01T00:00:00,2005-12-31T00:00:00,NaN,NaN,https://data.mips.climate.copernicus.eu/thredd...,ARC,44

In [6]:
df_cordex.nunique()

ds_id                     23488
path                     568405
size                          0
project                       1
domain                       27
institute                    39
driving_model                17
experiment_id                 5
ensemble                      6
rcm_name                     56
rcm_version                  11
time_frequency                6
variable                     25
version                     144
start_time                 1149
end_time                   2016
bbox                          0
level                         0
url                      568405
region                       14
horizontal_resolution         5
dtype: int64

In [7]:
list(df_cordex.domain.unique())

['ARC-44',
 'ARC-22',
 'SAM-22',
 'NAM-44',
 'AUS-44',
 'ANT-44',
 'MED-44',
 'AFR-44',
 'MNA-44',
 'EAS-22',
 'MED-11',
 'AUS-44i',
 'WAS-22',
 'NAM-22',
 'CAS-44',
 'WAS-44',
 'EUR-11',
 'CAS-22',
 'SAM-20',
 'SEA-22',
 'AUS-22',
 'CAM-44',
 'CAM-22',
 'SAM-44',
 'MNA-22',
 'EAS-44',
 'AFR-22']

In [8]:
list(df_cordex.region.unique())

['ARC',
 'SAM',
 'NAM',
 'AUS',
 'ANT',
 'MED',
 'AFR',
 'MNA',
 'EAS',
 'WAS',
 'CAS',
 'EUR',
 'SEA',
 'CAM']

In [9]:
list(df_cordex.horizontal_resolution.unique())

['44', '22', '11', '44i', '20']

## Write new catalog

In [10]:
from datetime import datetime, UTC

last_updated = datetime.now(UTC)
version = last_updated.strftime('v%Y%m%d')
cat_name = f"c3s-cordex_{version}.csv.gz"
cat_path = f"../intake/catalogs/c3s-cordex/{cat_name}"

df_cordex.to_csv(cat_path, index=False, compression="gzip")